### ISSUE TITLE
Still Active? -- Interested in contributions?

### ISSUE THREAD

**Issue by zyradyl** [CommanderMark/Troll-Quirk-Generator#15]
Hello!

I figure this might be odd, but I found your repository while trying to find something to use to write custom quirks. Since finding your code base I've dramatically increased the number of fish puns (lol), as well as starting work on a `trollifyCanon` function that converts words over to troll terminology as indicated on MSPAWiki.

I noticed you're a recreational coder and was unsure if you were interested in taking contributions on this project? Right now it's a pretty significant code size inflation. There's about 100 lines of fish puns, and I'm only up to the letter "M" on troll terms and its about 200 lines.

Regardless, thanks for the work on this project, it's been useful both for homestuck RP stuff and for me learning Typescript.

**Comment by CommanderMark** [comment]
Hello. Sorry about the late reply.

Generally I'd prefer it if this quick generator avoided changing the words inputted beyond an explicit typing quirk that a character has. I probably won't be accepting further terminology changes beyond what's already in the generator.

With that said I already have fish/cat puns implemented, so adding even more wouldn't hurt. If you want to contribute new code to the repository then the best way would be to [fork the project then make a pull request](https://guides.github.com/activities/forking/).

I'm going to close this issue but if you have further questions feel free to leave them below.
